replicaCount: 2

image:
  repository: ghcr.io/tlarbi/tol-frontend
  tag: "4.19.0"
  pullPolicy: Always

imagePullSecrets:

  - name: ghcr-secret

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  VITE_API_URL: "https://rag.taxonlineai.com"
  VITE_WS_URL: "wss://rag.taxonlineai.com"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: []

ingress:
  enabled: false
