{{- if .Values.jobs.fullPipeline.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobs.fullPipeline.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: tol-pipeline
    job: full-pipeline
spec:
  ttlSecondsAfterFinished: {{ .Values.jobs.fullPipeline.ttlSecondsAfterFinished }}
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: tol-pipeline
        job: full-pipeline
    spec:
      restartPolicy: OnFailure
      containers:
        - name: full-pipeline
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bash", "-c"]
          args:
            - |
              set -e
              echo "======================================"
              echo "  TaxOnline Full Pipeline"
              echo "  $(date)"
              echo "======================================"

              echo ""
              echo "=== [1/5] Extract PDFs → Silver/pages ==="
              python3 pipeline/01_extract/extract_pdf.py \
                --bronze-path "${BRONZE_PATH}" \
                --silver-path "${SILVER_PATH}" \
                --s3-endpoint "${S3_ENDPOINT}" \
                --s3-bucket "${S3_BUCKET}"

              echo ""
              echo "=== [2/5] Chunk pages → chunks.jsonl ==="
              python3 pipeline/02_chunk/chunk_text.py \
                --pages-dir "${SILVER_PATH}/pages" \
                --out "${SILVER_PATH}/chunks.jsonl" \
                --chunk-chars "${CHUNK_CHARS}" \
                --overlap-chars "${OVERLAP_CHARS}" \
                --min-chars "${MIN_CHARS}"

              echo ""
              echo "=== [3/5] Validate chunks ==="
              python3 pipeline/02_chunk/validate.py \
                --chunks "${SILVER_PATH}/chunks.jsonl" \
                --report "${SILVER_PATH}/_reports/validation.json"

              echo ""
              echo "=== [4/5] Index → Qdrant + OpenSearch ==="
              python3 pipeline/03_index/index_qdrant.py
              python3 pipeline/03_index/index_opensearch.py

              echo ""
              echo "=== [5/5] Verify index ==="
              python3 pipeline/03_index/verify_index.py \
                --chunks "${SILVER_PATH}/chunks.jsonl" \
                --report "${GOLD_PATH}/_reports/index_report.json"

              echo ""
              echo "======================================"
              echo "  PIPELINE COMPLETE — $(date)"
              echo "======================================"
          env:
            {{- include "tol-pipeline.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.jobs.fullPipeline.resources | nindent 12 }}
          volumeMounts:
            {{- include "tol-pipeline.volumeMount" . | nindent 12 }}
      volumes:
        {{- include "tol-pipeline.volume" . | nindent 8 }}
{{- end }}
