{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingClaim }}
# PersistentVolume — monte /data/datalake de la VM directement
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tol-pipeline-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tol-pipeline-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: tol-pipeline-pv
{{- end }}
{{- end }}
