image:
  repository: ghcr.io/tlarbi/tol-keyphrase-worker
  tag: develop-latest

resources:
  requests:
    memory: "1Gi"
    cpu: "250m"
  limits:
    memory: "3Gi"
    cpu: "1000m"

env:
  QDRANT_HOST: "qdrant-staging.storage.svc.cluster.local"
  QDRANT_PORT: "6333"
  QDRANT_COLLECTION: "tol-docs-v3"
  BATCH_SIZE: "10"
  POLL_SECONDS: "5"
