apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backup-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.vault.storeRef }}
    kind: ClusterSecretStore
  target:
    name: postgres-backup-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: {{ .Values.vault.path }}
        property: POSTGRES_HOST
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.vault.path }}
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.vault.path }}
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.vault.path }}
        property: POSTGRES_DB
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: {{ .Values.vault.path }}
        property: S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: {{ .Values.vault.path }}
        property: S3_SECRET_KEY
