apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-backup-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.vault.storeRef }}
    kind: ClusterSecretStore
  target:
    name: postgres-backup-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: {{ .Values.vault.postgresPath }}
        property: host
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.vault.postgresPath }}
        property: user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.vault.postgresPath }}
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.vault.postgresPath }}
        property: database
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: {{ .Values.vault.s3Path }}
        property: access_key
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: {{ .Values.vault.s3Path }}
        property: secret_key
