apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-falkordb
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: falkordb
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.falkordb.port }}
    targetPort: {{ .Values.falkordb.port }}
    name: redis
  selector:
    app.kubernetes.io/name: falkordb
    app.kubernetes.io/instance: {{ .Release.Name }}

