apiVersion: v1
kind: Service
metadata:
  name: {{ include "tol-kg.fullname" . }}
  labels:
    {{- include "tol-kg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "tol-kg.selectorLabels" . | nindent 4 }}
